* Generalizing type

** Passing an TM FG table instance

1. Suppose we have a generic TM FG table with the declared functions constituting the architecture (user's view, interface) of a tape machine.

2. Instances of this TM FG table to represent different implementations of the architecture. Say TM·Array·fg for a TM implemented as an array, and TM·Function·fg for a function implementation (for example the Natural_Number in the Java implementation).

3. Now suppose we have a function `map` that is given a TM_read, a TM_write, and a function.
   The map does not care how the TM is implemented.

   If these first two arguments are declared as TM FG type, then they can accept any fg table whether it be an Array implementation, a Function implementation, etc. The map can then pick the functions it needs, such as step, and rightmost, from the
   table, and thus get tape behavior. 

   This achieves what we wanted, a map function that can use a tape machine and does not care what the implementation of that tape machine is.

   However, the TM functions that map calls require to be given a first argument of that holds the TM instance data. Without this it can not know which machine is being operated on.
   Furthermore, the instance data type must match the TM fg table type.

   Given steps 1 through 3 we never passed in instance data to map, only a TM FG table insance. So map has a type, but not the data.

   
** Passing TM instance data, compile in the fg table.

1. As noted, `map` is given a TM_read, a TM_write, and a function. For these first two
   arguments, suppose we pass in the instance data, i.e. struct pointers.

2. The TM·Array struct will hold a base pointer to the array, and the head location.  The TM·Function struct would hold a handle recognized by the functions, or some state used by them.

3. Then we have a map function for each architecture type, and we compile into each of these a call to the correct default TM·fg table.  The map·Array will have compiled into it, TM·Array·fg, and the map·Function will have compiled into it TM·Function·fg etc.

4. This approach works, but we duplicate the map code many times just to get the types to match the calls.
   

** Passing in both, the TM instance data, and corresponding TM FG tables instances.

1. Say we have one generic `map` that given 5 arguments: TM_read (an instance), TM_read_fg, a TM_write (an instance), and TM_write_fg.

2. The instance parameters must be declared `void *` to prevent argument checking on them, otherwise it will be necessary to implement many map functions for each instance type combination.

3. This works, though we have no way to know if the correct type of instance data, that matches the fg table, was actually passed in.

4. We could create many wrapper functions to accomplish the instance data type check, then to call a central map function with `void *` instance data pointers. With any luck the optimizer would make this extra layer go away, so it will be efficient.  Still map now has 5 arguments instead the three that are natural for the problem.


** Using a "vtable"

1. All TM instance types are structs with a first field that points to the fg table,
   no matter the implementation type. This is not a serious requirement because
   each implementation type already has an struct for its implementation data. However it does make an instance bigger, and it is not clear that the optimizer will be able to
   discombobulation it all.

2. Then a generic fg table is created, where the functions have the signatures as specified
   in the FG table. However, each of these functions follows the fg table pointer in the
   the instance data given to it as a first argument, and then calls that function.

3. It works, and it is a tried and true method.

** Using a pointer pair ..

1. Instead of the instance data being called the 'TM type', a pair is the 'TM type',
   the first member of the pair points to an instance, the second to a corresponding
   fg table.

2. Again there are some generic TM functions, each accepts a pair as a first argument, and then calls the corresponding fg table function while giving it the instance pointer
   from the pair as the first argument.

3. This approach packs the same information as the vtable approach. If there is a
   one to one correspondence between instances and pairs, then it is larger by one pointer.

4. This is a type of 'link' from our continuations, but the tableau pointer is gone due
   to using a stack frame, and the continuation table pointer is gone due to flow through sequencing. Thus it is two pointers instead of 4.

5. Hopefully the optimizer would recognize that the pair pointers are redundant. They are only needed to ensure that the instance and fg table go together. 

** Instance curried dispatch function
 
1. In this case a pointer to a function is the 'TM type'. There is an enum that gives numeric tags to each of the functions in the FG struct instance.

2. The tag for the desired fg function to be called is passed as the first argument to the dispatch function, and the remaining arguments are for the fg function.

3. The dispatch function has the instance data and fg table pointer curried into it, so it then calls the correct fg function while handing it the correct instance data.

4. In C it is not immediately obvious how to create a function on the fly each time an
   instance is created, to curry the instance data into it, and then later how to call
   the newly created function.

** Self-typed Instance and dispatch function

1. With this method, an extra field is added to the instance data that identifies its type. Then a globally available TM specific dispatch function is called to run the desired fg function on the data.  It is similar to the dispatch function from above, but the instance data is an additional argument.

2. The dispatch function uses the type information to know which fg table to call. This type information could be a pointer to the appropriate fg table.

3. This approach differs from the vtable method in that all the arguments are given to the one TM dispatch function, and it figures out how to do the dispatch. There is not a wrapper-per-function. 

** Which approach?

We want to be able to declare an instance as a local variable, where it will end up being on the stack frame. We want to avoid heap allocation for performance reasons, but not exclude use of heap memory.

Dynamically created functions are out of the question. Dispatch approaches require the enum table so as to have tags. This is not show stopper. However, having one dispatch function means the argument types are not checked. That is a problem.

Doubled up argument, one for the instance, the other for the table, either require wrappers, or not checking that an instance really goes with the data. Besides it is a lot of typing.

The pointer pair approach requires the separate maintenance of the pair. When these are local variables, then the pair has to be tied to the instance. This would require the user to be aware of the existence of both the instance data and the pair, so as to pass them to an initializer.  This could be avoided if the pair would combined with the instance, but that
is identical to the vtable approach (the instance pointer no longer being needed).

So we are lead to the vtable. Though we are still hoping for the curried dispatch function - lol.


