#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  env_must_be="tester/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

set -e
set -x


cd "$REPO_HOME"/tester || exit 1

# remove test program dependency and objects
  rm_na scratchpad/{makefile-cc.deps,*.o} || true

# remove synthesized test sources
  rm_na cc/test_*.c || true

# remove built executables
  rm_na -f machine/* || true

set +x
echo "$(script_fn) done."
