#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# release test machine code

# input guards

  env_must_be="tester/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

set -e
set -x

  cd "$REPO_HOME"/tester || exit 1

  if [ ! -d scratchpad ]; then
    echo "$(script_fp):: no scratchpad directory"
    exit 1
  fi

  release_dir=$(release_dir)

  if [ ! -d ${release_dir} ]; then
    echo "$(script_fp):: no release directory to pull install files from"
    exit 1
  fi

  install_file machine/* ${release_dir} "ug+rx"




set +x
echo "$(script_fn) done."

