#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# pulls the library and include files down from the project release directory

# input guards

  env_must_be="tester/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

  cd "$REPO_HOME"/tester || exit 1

  if [ ! -d scratchpad ]; then
    echo "$(script_fp):: no scratchpad directory"
    exit 1
  fi

  release_dir=$(release_dir)

  if [ ! -d ${release_dir} ]; then
    echo "$(script_fp):: no release directory to pull install files from"
    exit 1
  fi

  cp -f ${release_dir}/libN.a scratchpad || true
  cp -f ${release_dir}/*.lib.c cc || true

echo "$(script_fn) done."

