#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# Pulls the library and include files down from the project release directory.
# Writes a list of installed files to a log file, `scratchpad/release_files.log`, while
# assuming no simultaneous writes.


# input guards
env_must_be="tester/tool🖉/env"
if [ "$ENV" != "$env_must_be" ]; then
  echo "$(script_fp):: error: must be run in the $env_must_be environment"
  exit 1
fi

cd "$REPO_HOME"/tester || exit 1

if [ ! -d scratchpad ]; then
  echo "$(script_fp):: no scratchpad directory"
  exit 1
fi

release_dir=$(release_dir)

if [ ! -d "$release_dir" ]; then
  echo "$(script_fp):: no release directory to pull install files from"
  exit 1
fi

log_file="scratchpad/release_files.log"
: >> "$log_file"  # Create and append to the log file

# Copy release files and track them
if ! cp -f "$release_dir/libN.a" scratchpad && realpath scratchpad/libN.a >> "$log_file"; then
  echo "$(script_fp):: warning: no libN.a found" >&2
fi
   
for file in "$release_dir"/*.lib.c; do
  if [ -f "$file" ]; then
    if cp -f "$file" cc; then
      realpath "cc/$(basename "$file")" >> "$log_file"
    else
      echo "$(script_fp):: warning: failed to copy $file" >&2
    fi
  else
    echo "$(script_fp):: warning: skipping non-regular file $file" >&2
  fi
done

echo "$(script_fn) done."
