#!/usr/bin/env python3

import sys
from template_N import N
from make_constants import make_constants_block

def write(code ,basename):
  filepath = "../cc/" + basename + ".lib.c" 
  with open(filepath, "w") as f:
    f.write(code)
  print("Generated " + filepath)
  

def main():
  """
  generates `.c` source code from templates
  """

  #----------------------------------------
  # N32 made from 1 digit, of 32 bits.
  
  type_name = "N32"
  digit_type = "uint32_t"
  digit_extent = 0

  constants_block = make_constants_block(type_name, digit_type, digit_extent)
  code = N(type_name ,digit_type ,digit_extent ,constants_block)
  write(code ,type_name);

  #----------------------------------------
  # N32 made from 4 digits, each 8 bits.

  type_name = "N32_4x8"
  digit_type = "uint8_t"
  digit_extent = 3

  constants_block = make_constants_block(type_name, digit_type, digit_extent)
  code = N(type_name ,digit_type ,digit_extent ,constants_block)
  write(code ,type_name);

if __name__ == "__main__":
  main()

