#!/usr/bin/env python3

import sys
from template_N import N

def write(code ,basename):
  filepath = "../cc/" + basename + ".lib.c" 
  with open(filepath, "w") as f:
    f.write(code)
  print("Generated " + filepath)
  

def main():
  """
  generates `.c` source code from templates
  """

  #----------------------------------------
  # N32 made from 1 digit, of 32 bits.
  
  type_name = "N32_1x32"
  digit_type = "uint32_t"
  digit_array_extent_type = "uint32_t"
  digit_array_extent = 0
  address_type = "uint64_t"

  code = N(
    type_name
    ,digit_type 
    ,digit_array_extent_type 
    ,digit_array_extent 
    ,address_type
  )
  write(code ,type_name);

  #----------------------------------------
  # N32 made from 4 digits, each 8 bits.

  type_name = "N32_1x32"
  digit_type = "uint32_t"
  digit_array_extent_type = "uint8_t"
  digit_array_extent = 3
  address_type = "uint64_t"

  code = N(
    type_name
    ,digit_type 
    ,digit_array_extent_type 
    ,digit_array_extent 
    ,address_type
  )
  write(code ,type_name);

if __name__ == "__main__":
  main()

