#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  env_must_be="developer/tool🖉/env"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

set -e
set -x


cd "$REPO_HOME"/developer || exit 1

# remove synthesized .c files
  rm_na cc/*

# remove object files, deps file, library, and whatever else is on the scratchpad if anything
  rm_na scratchpad/* || true

# remove built executables
  rm_na -f machine/* || true

set +x
echo "$(script_fn) done."
