#!/usr/bin/env python3

import sys
from template_test_N32_0 import test_N32_0

def write(code ,basename):
    filepath = "../cc/" + "test_" + basename + ".cli.c" 
    with open(filepath, "w") as f:
      f.write(code)
    print("Generated " + filepath)
    

def main():
    """
    generates `.c` source code from templates
    """

    # N32 processor native
    type_name = "N32"
    code = test_N32_0(namespace = type_name)
    write(code ,type_name + "_0");

    # N32 1 digit of 32 bits
    type_name = "N32_1x32"
    code = test_N32_0(namespace = type_name)
    write(code ,type_name + "_0");

    # N32 2 digits of 16 bits
    # type_name = "N32_4x8"
    # code = test_N32(namespace = type_name)
    # write(code ,type_name);

    # N32 4 digits of 8 bits
    type_name = "N32_4x8"
    code = test_N32_0(namespace = type_name)
    write(code ,type_name + "_0");


if __name__ == "__main__":
    main()
